title: "nʞʇn's Blog"
iconURL: assets/default-icon.png

markdown: kramdown
kramdown:
   math_engine: mathjax


# for a clean URL
permalink: :slug

social:
  twitter: Rhotav
  github: Rhotav

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 654
google_analytics: UA-NNNNNNNN-N
